from typing import Any
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).parent.parent.parent


def _get_configs() -> Any:
    """Load configuration from configs/configs.yaml."""
    configs_path = Path(PROJECT_ROOT, "configs", "configs.yaml")
    with open(configs_path) as f:
        return yaml.safe_load(f)


_configs = _get_configs()
REVOMON_REVODEX_ENDPOINT: str = _configs.get("REVOMON_REVODEX_ENDPOINT")
REVOMON_RAW_IMAGE_ENDPOINT: str = _configs.get("REVOMON_RAW_IMAGE_ENDPOINT")
REVOMON_NFT_IMAGE_ENDPOINT: str = _configs.get("REVOMON_NFT_IMAGE_ENDPOINT")
REVOMON_BASE_TYPES_IMAGE_ENDPOINT: str = _configs.get(
    "REVOMON_BASE_TYPES_IMAGE_ENDPOINT"
)
REVOMON_MOVES_ENDPOINT: str = _configs.get("REVOMON_MOVES_ENDPOINT")
POKEAPI_NATURES_ENDPOINT: str = _configs.get("POKEAPI_NATURES_ENDPOINT")
POKEAPI_NATURE_ENDPOINT: str = _configs.get("POKEAPI_NATURE_ENDPOINT")
POKEAPI_MEDICINE_CATEGORY_ENDPOINT: str = _configs.get(
    "POKEAPI_MEDICINE_CATEGORY_ENDPOINT"
)
POKEAPI_ITEM_ENDPOINT: str = _configs.get("POKEAPI_ITEM_ENDPOINT")
REVOMON_FILE: Path = Path(PROJECT_ROOT, _configs.get("REVOMON_FILE"))
EVOLUTIONS_FILE: Path = Path(PROJECT_ROOT, _configs.get("EVOLUTIONS_FILE"))
ABILITIES_FILE: Path = Path(PROJECT_ROOT, _configs.get("ABILITIES_FILE"))
UNKNOWN_ABILITIES_FILE: Path = Path(
    PROJECT_ROOT, _configs.get("UNKNOWN_ABILITIES_FILE")
)
BASE_TYPES_FILE: Path = Path(PROJECT_ROOT, _configs.get("BASE_TYPES_FILE"))
MOVEPOOLS_FILE: Path = Path(PROJECT_ROOT, _configs.get("MOVEPOOLS_FILE"))
MOVES_FILE: Path = Path(PROJECT_ROOT, _configs.get("MOVES_FILE"))
TYPE_CHARTS_FILE: Path = Path(PROJECT_ROOT, _configs.get("TYPE_CHARTS_FILE"))
MISSING_TYPE_CHARTS_FILE: Path = Path(
    PROJECT_ROOT, _configs.get("MISSING_TYPE_CHARTS_FILE")
)
NATURES_FILE: Path = Path(PROJECT_ROOT, _configs.get("NATURES_FILE"))
MEDICINES_FILE: Path = Path(PROJECT_ROOT, _configs.get("MEDICINES_FILE"))
ITEMS_FILE: Path = Path(PROJECT_ROOT, _configs.get("ITEMS_FILE"))
FRUITYS_FILE: Path = Path(PROJECT_ROOT, _configs.get("FRUITYS_FILE"))
CAUGHT_REVOMON_FILE: Path = Path(PROJECT_ROOT, _configs.get("CAUGHT_REVOMON_FILE"))
CAUGHT_REVOMON_SCAN_STATE_FILE: Path = Path(
    PROJECT_ROOT, _configs.get("CAUGHT_REVOMON_SCAN_STATE_FILE")
)
CAPSULES_FILE: Path = Path(PROJECT_ROOT, _configs.get("CAPSULES_FILE"))
TYPE_CHART_IMAGES_DIR: Path = Path(PROJECT_ROOT, _configs.get("TYPE_CHART_IMAGES_DIR"))
BASE_TYPES_IMAGES_DIR: Path = Path(PROJECT_ROOT, _configs.get("BASE_TYPES_IMAGES_DIR"))
REVOMON_RAW_IMAGES_DIR: Path = Path(
    PROJECT_ROOT, _configs.get("REVOMON_RAW_IMAGES_DIR")
)
REVOMON_NFT_IMAGES_DIR: Path = Path(
    PROJECT_ROOT, _configs.get("REVOMON_NFT_IMAGES_DIR")
)
REVOMON_IMAGES_DOWNLOAD_MANIFEST_FILE: Path = Path(
    PROJECT_ROOT, _configs.get("REVOMON_IMAGES_DOWNLOAD_MANIFEST")
)
USER_AGENT: str = _configs.get("USER_AGENT")
GRADEX_DB_PATH: Path = Path(PROJECT_ROOT, _configs.get("GRADEX_DB_PATH"))

__all__ = [
    "PROJECT_ROOT",
    "REVOMON_REVODEX_ENDPOINT",
    "REVOMON_RAW_IMAGE_ENDPOINT",
    "REVOMON_NFT_IMAGE_ENDPOINT",
    "REVOMON_BASE_TYPES_IMAGE_ENDPOINT",
    "REVOMON_MOVES_ENDPOINT",
    "POKEAPI_NATURES_ENDPOINT",
    "POKEAPI_NATURE_ENDPOINT",
    "POKEAPI_MEDICINE_CATEGORY_ENDPOINT",
    "POKEAPI_ITEM_ENDPOINT",
    "REVOMON_FILE",
    "EVOLUTIONS_FILE",
    "ABILITIES_FILE",
    "UNKNOWN_ABILITIES_FILE",
    "BASE_TYPES_FILE",
    "MOVEPOOLS_FILE",
    "MOVES_FILE",
    "TYPE_CHARTS_FILE",
    "MISSING_TYPE_CHARTS_FILE",
    "NATURES_FILE",
    "MEDICINES_FILE",
    "ITEMS_FILE",
    "FRUITYS_FILE",
    "CAUGHT_REVOMON_FILE",
    "CAUGHT_REVOMON_SCAN_STATE_FILE",
    "CAPSULES_FILE",
    "TYPE_CHART_IMAGES_DIR",
    "BASE_TYPES_IMAGES_DIR",
    "REVOMON_RAW_IMAGES_DIR",
    "REVOMON_NFT_IMAGES_DIR",
    "REVOMON_IMAGES_DOWNLOAD_MANIFEST_FILE",
    "USER_AGENT",
    "GRADEX_DB_PATH",
]
